using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Xigadee
{
    /// <summary>
    /// This interface is used to log payload metadata to a central source.
    /// </summary>
    public interface IBoundaryLogger
    {
        /// <summary>
        /// This interface is used to log payload data when a message is either incoming or outgoing from the system.
        /// </summary>
        /// <param name="direction">The direction of the message.</param>
        /// <param name="payload">The payload.</param>
        /// <param name="ex">Any exception generated by the attempt. If this is not null then you can assume that the incoming or outgoing action was not successful.</param>
        void Log(ChannelDirection direction, TransmissionPayload payload, Exception ex = null, Guid? batchId = null);
        /// <summary>
        /// This method is used to record a batch poll so that messages can be reconciled against the request.
        /// </summary>
        /// <param name="requested">The number of messages requested.</param>
        /// <param name="actual">The actual number returned.</param>
        /// <param name="channelId">The channel id for the request.</param>
        /// <returns></returns>
        Guid BatchPoll(int requested, int actual, string channelId);
    }
}
